sequenceDiagram
    Alice->>Bob: Hello Bob
    alt is sick
        Bob->>Alice: Not so good
    else is well
        Bob->>Alice: Feeling fresh
    end
    opt Extra response
        Bob->>Alice: Thanks for asking
    end
