//! Differential tests: the Rust dagre port must reproduce dagre-d3-es 7.0.14
//! exactly. Fixtures are generated by the Node harness (`gen.mjs`) which runs
//! the original JS implementation.

use std::cell::RefCell;
use std::rc::Rc;

use mermaid_rust::dagre;
use mermaid_rust::dagre::types::{EdgeLabel, GraphLabel, NodeLabel, edge_ref, node_ref};
use mermaid_rust::graphlib::{Graph, GraphOptions};
use serde_json::Value;

fn build_graph(spec: &Value) -> dagre::types::LayoutGraph {
    let mut g: dagre::types::LayoutGraph = Graph::new(GraphOptions {
        multigraph: Some(true),
        compound: Some(true),
        ..Default::default()
    });

    let gspec = &spec["graph"];
    let mut label = GraphLabel::default();
    if let Some(v) = gspec["rankdir"].as_str() {
        v.clone_into(&mut label.rankdir);
    }
    if let Some(v) = gspec["nodesep"].as_f64() {
        label.nodesep = v;
    }
    if let Some(v) = gspec["ranksep"].as_f64() {
        label.ranksep = v;
    }
    if let Some(v) = gspec["edgesep"].as_f64() {
        label.edgesep = v;
    }
    if let Some(v) = gspec["marginx"].as_f64() {
        label.marginx = v;
    }
    if let Some(v) = gspec["marginy"].as_f64() {
        label.marginy = v;
    }
    g.set_graph(Rc::new(RefCell::new(label)));

    for n in spec["nodes"].as_array().expect("nodes") {
        let v = n["v"].as_str().expect("node id");
        g.set_node_with(
            v,
            node_ref(NodeLabel {
                width: n["width"].as_f64().expect("width"),
                height: n["height"].as_f64().expect("height"),
                ..Default::default()
            }),
        );
    }
    // Parents are set after all nodes exist, mirroring the JS harness which
    // calls setParent during the same loop; order does not matter because
    // setParent creates missing nodes with default labels in both impls only
    // when the parent was not yet added — the fixtures always declare parents
    // as explicit nodes too, in the same insertion order.
    for n in spec["nodes"].as_array().expect("nodes") {
        if let Some(parent) = n["parent"].as_str() {
            g.set_parent(n["v"].as_str().expect("node id"), Some(parent));
        }
    }

    for e in spec["edges"].as_array().expect("edges") {
        let mut label = EdgeLabel::default();
        let l = &e["label"];
        if let Some(v) = l["minlen"].as_f64() {
            label.minlen = v;
        }
        if let Some(v) = l["weight"].as_f64() {
            label.weight = v;
        }
        if let Some(v) = l["width"].as_f64() {
            label.width = v;
        }
        if let Some(v) = l["height"].as_f64() {
            label.height = v;
        }
        if let Some(v) = l["labeloffset"].as_f64() {
            label.labeloffset = v;
        }
        if let Some(v) = l["labelpos"].as_str() {
            v.clone_into(&mut label.labelpos);
        }
        g.set_edge(
            e["v"].as_str().expect("edge v"),
            e["w"].as_str().expect("edge w"),
            edge_ref(label),
            e["name"].as_str(),
        );
    }

    g
}

fn assert_close(actual: f64, expected: f64, what: &str) {
    assert!(
        (actual - expected).abs() <= 1e-6,
        "{what}: got {actual}, expected {expected}"
    );
}

fn run_fixture(name: &str) {
    let path = format!("{}/tests/fixtures/{name}.json", env!("CARGO_MANIFEST_DIR"));
    let data: Value = serde_json::from_str(&std::fs::read_to_string(&path).expect("fixture file"))
        .expect("fixture json");
    let g = build_graph(&data["spec"]);
    dagre::layout(&g);

    let expected = &data["expected"];

    let graph = g.graph();
    let graph = graph.borrow();
    assert_close(
        graph.width,
        expected["graph"]["width"].as_f64().expect("width"),
        "graph.width",
    );
    assert_close(
        graph.height,
        expected["graph"]["height"].as_f64().expect("height"),
        "graph.height",
    );

    for (v, en) in expected["nodes"].as_object().expect("nodes") {
        let node = g.node(v).unwrap_or_else(|| panic!("missing node {v}"));
        let node = node.borrow();
        assert_close(
            node.x.expect("x"),
            en["x"].as_f64().expect("x"),
            &format!("{v}.x"),
        );
        assert_close(
            node.y.expect("y"),
            en["y"].as_f64().expect("y"),
            &format!("{v}.y"),
        );
        assert_close(
            node.width,
            en["width"].as_f64().expect("w"),
            &format!("{v}.width"),
        );
        assert_close(
            node.height,
            en["height"].as_f64().expect("h"),
            &format!("{v}.height"),
        );
    }

    for ee in expected["edges"].as_array().expect("edges") {
        let v = ee["v"].as_str().expect("v");
        let w = ee["w"].as_str().expect("w");
        let name = ee["name"].as_str();
        let id = format!("{v}->{w}:{name:?}");
        let label = g
            .edge(v, w, name)
            .unwrap_or_else(|| panic!("missing edge {id}"));
        let label = label.borrow();
        let exp_points = ee["points"].as_array().expect("points");
        let points = label.points.as_ref().expect("points");
        assert_eq!(points.len(), exp_points.len(), "{id} point count");
        for (i, (p, ep)) in points.iter().zip(exp_points).enumerate() {
            assert_close(p.x, ep["x"].as_f64().expect("px"), &format!("{id} p{i}.x"));
            assert_close(p.y, ep["y"].as_f64().expect("py"), &format!("{id} p{i}.y"));
        }
        match ee["x"].as_f64() {
            Some(x) => {
                assert_close(label.x.expect("label x"), x, &format!("{id}.x"));
                assert_close(
                    label.y.expect("label y"),
                    ee["y"].as_f64().expect("label y"),
                    &format!("{id}.y"),
                );
            }
            None => assert!(label.x.is_none(), "{id}: unexpected label x {:?}", label.x),
        }
    }
}

macro_rules! fixture_tests {
    ($($name:ident),* $(,)?) => {
        $(
            #[test]
            fn $name() {
                run_fixture(stringify!($name));
            }
        )*
    };
}

fixture_tests!(
    chain,
    diamond_labels,
    cycle,
    self_loop,
    multi_edge,
    clusters,
    lr_direction,
    bt_direction,
    rl_direction,
    numeric_names,
    disconnected,
    random_7,
    random_42,
    random_99,
    random_1234,
    random_clusters_5,
    random_clusters_77,
);
