gitGraph
    commit id: "Alpha"
    commit id: "Beta" tag: "v1.0"
    branch feature
    commit id: "Gamma" type: HIGHLIGHT
    checkout main
    commit id: "Delta" type: REVERSE
    cherry-pick id: "Gamma"
    merge feature tag: "v2.0"
