gitGraph
    commit id: "one"
    commit id: "two"
    branch develop
    checkout develop
    commit id: "three"
    commit id: "four"
    checkout main
    merge develop id: "m1"
    commit id: "five"
    commit id: "six"
