%%{init: {"gitGraph": {"showCommitLabel": false}}}%%
gitGraph TB:
    commit id: "a"
    commit id: "b" type: HIGHLIGHT
    branch feat
    commit id: "c"
    branch sub
    commit id: "d"
    checkout main
    commit id: "e"
    merge feat id: "m"
