graph TD
    E1[E] --> E2[E]
    E1 --> Plus["+"]
    E1 --> T1[T]
    E2 --> T2[T]
    T2 --> F1[F]
    F1 --> n1[n]
    T1 --> T3[T]
    T1 --> Times["*"]
    T1 --> F2[F]
    T3 --> F3[F]
    F3 --> n2[n]
    F2 --> n3[n]
